package com.imaginea;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class EvenFibonacciNumber {
	public long getSumofEvenValuedNum(int limit) {
		long[] fib = new long[3];
		fib[0] = 0;
		fib[1] = 1;
		long sumOfEvenValuedNo = 0;
		//System.out.println("fibonacci Series...");
		while (true) {
			fib[2] = fib[0] + fib[1];
			fib[0] = fib[1];
			fib[1] = fib[2];
			if (fib[2] > limit)
				break;
			if (fib[2] % 2 == 0)
				sumOfEvenValuedNo += fib[2];
		}
		//System.out.println("\nSum of the even-valued terms in fibonacci-series is "+sumOfEvenValuedNo);
		return sumOfEvenValuedNo;
	}
	
	public static void main(String[] args) {
		EvenFibonacciNumber fibonacciNumber = new EvenFibonacciNumber();
		fibonacciNumber.getSumofEvenValuedNum(10);
	}
}
